project_id = "fxfljmqpckujerawkwhq"

[functions]
  [functions.ai-form-fill]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.elevenlabs-postcall]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-document]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.twilio-voice-webhook]
    verify_jwt = false
  [functions.voice-speak]
    verify_jwt = true
  [functions.voice-transcribe]
    verify_jwt = true
  [functions.stripe-checkout]
    verify_jwt = true
  [functions.stripe-portal]
    verify_jwt = true
  [functions.stripe-webhook]
    verify_jwt = false
