import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, Search, FolderPlus, CheckCircle2, CalendarDays, FileText, Receipt, Users } from "lucide-react";
import { WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";
import { FolderCard } from "@/components/workspace/FolderCard";
import { JobFolderView, type JobFolderData } from "@/components/workspace/JobFolderView";
import { workspaceGroups } from "@/components/workspace/navigation";
import WorkspaceHub from "@/pages/app/WorkspaceHub";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const sample: JobFolderData[] = [
  { job: { id: "patio", title: "Backyard patio", status: "in_progress", address: "124 Cedar Lane · Portland, OR", scheduled_start: "2026-10-12T16:00:00Z", budget: 12400, customers: { name: "Avery Bennett" }, description: "Remove the existing patio and prepare a new concrete outdoor living space. Confirm access, final dimensions, finish, and joint layout before the pour." }, estimates: [{ id: "e1", title: "Patio replacement", detail: "Accepted · Sample estimate", amount: 12400 }], invoices: [{ id: "i1", title: "Deposit invoice", detail: "Paid · Sample invoice", amount: 6200 }], time: [{ id: "t1", title: "Monday · Site preparation", detail: "8.0 hours · Approved" }], crew: ["Alex", "Jordan"] },
  { job: { id: "driveway", title: "Driveway replacement", status: "scheduled", address: "860 Maple Court · Gresham, OR", scheduled_start: "2026-10-14T16:00:00Z", budget: 18500, customers: { name: "Casey Parker" }, description: "Remove and replace the driveway. Review site access and drainage before demolition. This is a sample project for exploring the new workspace." }, estimates: [{ id: "e2", title: "Driveway proposal", detail: "Accepted · Sample estimate", amount: 18500 }], invoices: [], time: [], crew: ["Alex"] },
  { job: { id: "walkway", title: "Front entry walkway", status: "on_hold", address: "42 Oak Street · Hood River, OR", scheduled_start: null, budget: 8200, customers: { name: "Riley Morgan" }, description: "New front entry walkway. Waiting on the customer's finish selection before confirming the schedule." }, estimates: [{ id: "e3", title: "Walkway proposal", detail: "Sent · Sample estimate", amount: 8200 }], invoices: [], time: [], crew: [] },
];
export default function WorkspacePreview() {
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const section = params.get("section") || "/app";
  const selected = sample.find(x => x.job.id === params.get("job"));
  const go = (path: string) => { setSearch(""); setParams({ section: path }); };
  const open = (id: string) => setParams({ section: "/app/jobs", job: id });
  const visible = sample.filter(x => `${x.job.title} ${x.job.customers?.name} ${x.job.address}`.toLowerCase().includes(search.toLowerCase()) && (filter === "all" || x.job.status === filter));
  const item = workspaceGroups.flatMap(g => g.items).find(i => i.to === section);
  const heading = item?.label || "Ask AI";
  const folders = <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map(({ job }) => <FolderCard key={job.id} job={job} onOpen={() => open(job.id)} />)}</div>;
  let content;
  if (selected) content = <JobFolderView key={selected.job.id} data={selected} onBack={() => go("/app/jobs")} onNavigate={go} />;
  else if (section === "/app/money" || section === "/app/company") content = <WorkspaceHub section={section.endsWith("money") ? "Money" : "Company"} preview />;
  else if (section === "/app" || section === "/app/jobs") content = <div className="space-y-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.2em] text-primary">A place for everything</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{section === "/app" ? "A clearer view of your business." : "Your job folders."}</h1><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">{section === "/app" ? "Less searching. More getting things done. Your customers, projects, and money—organized in one workspace." : "One folder per project. Scope, estimates, invoices, and crew hours stay together."}</p></div><Button onClick={() => go(section === "/app" ? "/app/jobs" : "/app/customers")}><FolderPlus className="h-4 w-4" />{section === "/app" ? "Explore jobs" : "View customers"}</Button></div>
    {section === "/app" && <><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[{ label: "Job folders", value: "3", detail: "2 active or scheduled", icon: CalendarDays, to: "/app/jobs" }, { label: "Estimates", value: "3", detail: "1 awaiting a response", icon: FileText, to: "/app/estimates" }, { label: "Payments received", value: "$6,200", detail: "Sample deposit payment", icon: Receipt, to: "/app/invoices" }, { label: "Customers", value: "3", detail: "Every relationship, organized", icon: Users, to: "/app/customers" }].map(tile => <button key={tile.label} onClick={() => go(tile.to)} className="min-w-0 rounded-xl border border-border bg-card p-4 text-left hover:border-primary/60 sm:p-5"><div className="flex items-center justify-between gap-2 text-xs text-muted-foreground">{tile.label}<tile.icon className="h-4 w-4 shrink-0" /></div><p className="mt-4 text-2xl font-semibold sm:text-3xl">{tile.value}</p><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{tile.detail}</p></button>)}</div><div className="flex flex-wrap items-center gap-3 rounded-xl border border-primary/20 bg-primary/5 px-5 py-4"><CheckCircle2 className="h-5 w-5 text-primary" /><p className="flex-1 text-sm">Your workspace, without the clutter.</p><button onClick={() => go("/app/money")} className="flex items-center gap-2 text-xs text-primary">Open money <ArrowRight className="h-3 w-3" /></button></div></>}
    <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{section === "/app" ? "Recent job folders" : "All projects"}</h2><span className="text-xs text-muted-foreground">{visible.length} folders</span></div>{section === "/app/jobs" && <div className="mb-6 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Search sample folders" placeholder="Search projects or customers…" className="pl-10" value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label="Filter sample jobs" className="min-h-10 rounded-md border border-border bg-card px-3 text-sm" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All statuses</option><option value="in_progress">In progress</option><option value="scheduled">Scheduled</option><option value="on_hold">On hold</option></select></div>}{folders}{visible.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">No folders match. Try another search or status.</p>}</section>
    {section === "/app" && <section><h2 className="mb-5 text-lg font-semibold">Browse your workspace</h2><div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{workspaceGroups.slice(1).map(g => <button key={g.label} onClick={() => go(g.to)} className="rounded-xl border border-border bg-card p-5 text-left hover:border-primary/60"><g.icon className="mb-5 h-5 w-5 text-primary" /><p className="text-sm font-medium">{g.label}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{g.description}</p></button>)}</div></section>}
  </div>;
  else if (section === "/app/customers") content = <div><h1 className="mb-3 text-3xl font-semibold">Customers</h1><p className="mb-8 text-sm text-muted-foreground">Open a customer's project folder.</p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{sample.map(({job}) => <button key={job.id} onClick={() => open(job.id)} className="rounded-2xl border border-border bg-card p-6 text-left hover:border-primary/60"><span className="mb-6 grid h-12 w-12 place-items-center rounded-full bg-primary/10 text-primary">{job.customers!.name.split(" ").map(n => n[0]).join("")}</span><h2 className="font-semibold">{job.customers!.name}</h2><p className="mt-2 text-xs text-muted-foreground">{job.title}</p><p className="mt-6 text-xs text-primary">Open project →</p></button>)}</div></div>;
  else if (["/app/estimates", "/app/invoices", "/app/calendar", "/app/time", "/app/crew"].includes(section)) content = <div><h1 className="mb-3 text-3xl font-semibold">{heading}</h1><p className="mb-8 text-sm text-muted-foreground">Sample records. Open a folder to explore related details.</p><div className="space-y-3">{sample.map(({job, estimates, invoices, crew}) => <button key={job.id} onClick={() => open(job.id)} className="flex w-full flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-5 text-left hover:border-primary/60"><div><p className="text-sm font-semibold">{job.title}</p><p className="mt-1 text-xs text-muted-foreground">{job.customers!.name}</p></div><span className="text-xs text-primary">{section.endsWith("estimates") ? `${estimates.length} estimate` : section.endsWith("invoices") ? `${invoices.length} invoices` : section.endsWith("crew") ? `${crew.length} assigned` : "Open project"} →</span></button>)}</div></div>;
  else content = <div className="rounded-2xl border border-border bg-card p-8"><h1 className="text-2xl font-semibold">{heading}</h1><p className="mt-4 max-w-lg text-sm leading-7 text-muted-foreground">This preview demonstrates the new workspace organization. {heading} remains available in your signed-in FastTract app; this sample workspace does not change account settings or send messages.</p><Button className="mt-6" variant="outline" onClick={() => go("/app")}>Back to overview</Button></div>;
  return <WorkspaceFrame path={section} name="Morgan" company="Demo Concrete Co." preview>{content}<footer className="mt-12 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5 text-[11px] leading-5 text-muted-foreground"><span>Design preview · Fictional projects and amounts · No account changes</span><Link to="/login" className="text-primary">Go to FastTract sign in →</Link></footer></WorkspaceFrame>;
}
