// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-customers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_customers_default = defineTool({
  name: "list_customers",
  title: "List customers",
  description: "List customers visible to the signed-in user's organization.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive name/email substring filter."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("customers").select("id,name,email,phone,address,created_at").order("created_at", { ascending: false }).limit(limit);
    if (search) q = q.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { customers: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-customer.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_customer_default = defineTool2({
  name: "create_customer",
  title: "Create customer",
  description: "Create a new customer record in the signed-in user's active organization.",
  inputSchema: {
    name: z2.string().trim().min(1),
    email: z2.string().email().optional(),
    phone: z2.string().optional(),
    address: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    const { data: memberships, error: mErr } = await client.from("organization_members").select("organization_id").eq("user_id", ctx.getUserId()).limit(1);
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const orgId = memberships?.[0]?.organization_id;
    if (!orgId) return { content: [{ type: "text", text: "No organization found for this user." }], isError: true };
    const { data, error } = await client.from("customers").insert({ ...input, organization_id: orgId }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created customer ${data.id}` }], structuredContent: { customer: data } };
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_jobs_default = defineTool3({
  name: "list_jobs",
  title: "List jobs",
  description: "List jobs for the signed-in user's organization, most recent first.",
  inputSchema: {
    status: z3.string().optional().describe("Optional status filter (e.g. scheduled, in_progress, completed)."),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb3(ctx).from("jobs").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { jobs: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "List leads",
  description: "List leads for the signed-in user's organization, most recent first.",
  inputSchema: {
    status: z4.string().optional().describe("Optional status filter (e.g. new, contacted, qualified, lost)."),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { leads: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-estimates.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_estimates_default = defineTool5({
  name: "list_estimates",
  title: "List estimates",
  description: "List estimates for the signed-in user's organization, most recent first.",
  inputSchema: {
    status: z5.string().optional().describe("Optional status filter (e.g. draft, sent, accepted, declined)."),
    limit: z5.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb5(ctx).from("estimates").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { estimates: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fxfljmqpckujerawkwhq";
var mcp_default = defineMcp({
  name: "fasttract-mcp",
  title: "FastTract MCP",
  version: "0.1.0",
  instructions: "Tools for FastTract, a contractor CRM. Use these to read and create the signed-in user's customers, leads, estimates, and jobs. All calls run under the user's Row-Level Security context.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_customers_default, create_customer_default, list_jobs_default, list_leads_default, list_estimates_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
